### ISSUE TITLE
Logs showing one port mapping, but not updating after gluetun changes port

### ISSUE THREAD

**Issue by Nagamakii** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#16]
Hello,

Not sure if I set things up wrong, but I am having an issue where the sync mod is only mapping the port to the qbittorent container once when the containers spin up, but doesn't update as the gluetun container changes ports.

![image](https://github.com/user-attachments/assets/02e9f307-b0b4-489b-b279-a1f74e267efa)

^ qbittorent logs

![image](https://github.com/user-attachments/assets/c61f15a0-6e1a-4c95-b9b7-73166fb8d26c)

^ gluetun logs

You can see that while the gluetun logs have updated the port many times, the sync mod logs only updated once. I have checked inside of the webUI of qbittorent to see if the logs just aren't reporting when the port changes but no luck.

```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /mnt/armin/configs/gluetun:/gluetun
      - /mnt/armin/configs/gluetun/config.toml:/gluetun/auth/config.toml
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASS}
      - SERVER_COUNTRIES=United States
      - VPN_PORT_FORWARDING=on
      - HTTP_CONTROL_SERVER_ADDRESS=:8030
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c "echo {{PORTS}}"
    ports:
      - 8030:8030 # control server
      - 8020:8020 # qbittorent
      - 8989:8989 # sonarr

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    volumes:
      - /mnt/armin/configs/qbittorent:/config
      - /mnt/armin/media/unsorted:/downloads
    environment:
      - WEBUI_PORT=8020
      - TZ=US/CST
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_GTN_API_KEY=${API_KEY}
      - GSP_QBT_USERNAME=${Q_USERNAME}
      - GSP_QBT_PASSWORD=${Q_PASS}
      - GSP_GTN_ADDR=http://172.18.0.2:8030
      - GSP_SLEEP=45
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - TZ=America/CST
    volumes:
      - /home/sonarr:/config
      - /mnt/armin/media:/data
    restart: unless-stopped

```
    
Above is my docker-compose.yml file. I have also made sure that my .toml file is accurate:
    
```
[[roles]]
name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"
routes = ["GET /v1/openvpn/portforwarded"]
auth = "apikey"
# This is an example, generate your own. See bellow.
apikey = "KEY"
```

I did notice that the port that gets forwarded is under the [port forwarding] section instead of the [http server] section.

![image](https://github.com/user-attachments/assets/dd8b2d52-ba92-46aa-8ddd-0568ee855298)

Any help is greatly appreciated!
