### ISSUE TITLE
linuxserver/qbittorrent version 5.0.4-r0-ls389 onwards causes getting docker mods to fail when behind a gluetun VPN

### ISSUE THREAD

**Issue by arteeh** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#26]
Log:
[mod-init] Running Docker Modification Logic
[mod-init] Adding t-anc/gsp-qbittorent-gluetun-sync-port-mod:latest to container
[mod-init] (ERROR) Couldn't fetch auth token from ghcr.io, switching to offline mode for t-anc/gsp-qbittorent-gluetun-sync-port-mod:latest
[mod-init] (ERROR) OFFLINE: t-anc/gsp-qbittorent-gluetun-sync-port-mod:latest not found in modcache, skipping

I don't think this issue can be fixed on this end, but I wanted to put it out there in case people with the same error come looking in this issue section.

linuxserver/qbittorrent issue: https://github.com/linuxserver/docker-qbittorrent/issues/380

For me this error doesn't happen all the time, so i've had some success just stopping and starting the stack until it works. Also, I have the VueTorrent docker mod as well and that one seems to work OK. Maybe only the first docker mod in the list fails.

Workaround is to revert to 5.0.4-r0-ls388, or to use the standalone container instead of docker mods.

**Comment by asardaes** [comment]
Does your compose file include this for the qbittorrent container?

```yaml
        depends_on:
          gluetun:
            condition: service_healthy
```

**Comment by arteeh** [comment]
Ok yeah it was the missing health check. Makes a lot of sense in hindsight.

I had to manually add the healthcheck in my compose file as well for this to work:
```
healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 1
```
