### ISSUE TITLE
Error retrieving port from Qbittorrent API

### ISSUE THREAD

**Issue by johnross2007** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#9]
I get this error message:
`curl: (22) The requested URL returned error: 403
09/15/24 16:16:25 [GSP] - Error retrieving port from Qbittorrent API.`

I'm using paid ProtonVPN. I cannot access the WebUI.

Compose File:

```
services:

  gluetun:
    image: ghcr.io/qdm12/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /redacted/gluetun:/gluetun
    environment:
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=redacted
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on


  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_SLEEP=120
      - GSP_MINIMAL_LOGS=false
      - GSP_SKIP_INIT_CHECKS=true
    volumes:
      - /redacted/config:/config
      - /redacted/webui:/webui
    network_mode: container:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
```
